import type { Metadata } from 'next'
import { Lexend_Deca, Karla } from 'next/font/google';
import '../globals.css'
import { NavBar } from '../components/storyBookComponents/navbar/navBar';
import BackgroundTime from '../components/backendComponents/timeDepender/backgroundTimeSmall';

import { useTranslation } from 'next-i18next';



export const metadata: Metadata = {
  title: 'mat-app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <BackgroundTime></BackgroundTime>
      {children}
      <NavBar />
    </>
  )
}
