import '../../../globals.css'

import type { Metadata } from 'next'
import { Karla, Lexend_Deca } from 'next/font/google'
import { redirect } from 'next/navigation'
import { getServerSession } from 'next-auth'
import { useTranslation } from 'next-i18next'

export const metadata: Metadata = {
    title: 'mat-app',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
    params: { lng },
}: {
    children: React.ReactNode
    params: {
        lng: string
    }
}) {
    const session = await getServerSession()

    return <main className={['backgroundGlobal'].join(' ')}>{children}</main>
}
