import type { Metadata } from 'next'
import { Lexend_Deca, Karla } from 'next/font/google';
import '../../globals.css'
import { getServerSession } from "next-auth";
import { redirect } from 'next/navigation'

import { useTranslation } from 'next-i18next';


export const metadata: Metadata = {
  title: 'mat-app',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode,
  params: {
    lng: string
  }
}) {
  const session = await getServerSession();

  return (
    <main className={["backgroundGlobal"].join(" ")}>
      {children}
    </main>
  )
}
